### ISSUE TITLE
20190414 회의록

### ISSUE THREAD

**Issue by krlee407** [tobigstudio/employment_photo_generator#1]
### 프로젝트 방향
- 증명사진에서 주어진 취업사진에 얼굴을 바꾸는 모델을 만든다.
  1. 증명사진에서 얼굴을 크롭 `A`
  2. 취업사진에서 얼굴을 크롭 `B`
  3. `A`를 `B` 사이즈로 리사이징하여 취업사진에 그대로 이식
  4. GAN 모델을 이용하여 자연스러운 사진으로 변환
![KakaoTalk_Photo_2019-04-14-19-01-15](https://user-images.githubusercontent.com/26590532/56091273-ec836080-5ee7-11e9-97b1-45dc659af56a.jpeg)

### TODO
- [ ] 증명사진 -> 취업사진으로 얼굴을 이식하는 스크립트 작성 ( @KwonHyeMin )
  - 만들어야할 함수
    - 얼굴 잘라내기
      - input : 원본사진 (증명 or 취업사진)
      - output :  얼굴부분만
    - 얼굴 합치기
      - input : 잘린 얼굴 사진, 얼굴만 잘린 사진
      - output : 두 input이 합쳐진 사진
- [ ] 합성사진을 자연스럽게 만드는 모델 테스트 해보기 ( [exGAN](https://github.com/zhangqianhui/Exemplar-GAN-Eye-Inpainting-Tensorflow) ) ( @krlee407 )
  - 주어진 합성사진을 자연스러운 사진으로 변경하는 모델 필요
  - 모델에서 준 데이터로 트레이닝 / 테스트를 해보면서 실제로 재현이 가능한지 확인
  - 참고 : https://bdol.github.io/exemplar_gans/
- 데이터셋 구축
  - 네이버 카페/게시판, 인스타 계정명을 입력하면 이에 해당하는 이미지 긁어오는 크롤러 만들기
    - [ ] 네이버 카페/게시판 ( @LEEMINJOO , @soomin-kang )
    - 인스타 계정 ( 보류 )
  - 취업사진일 필요가 있을까? 일단 다 긁고 나중에 생각
  - 얼마나 필요한가? 일단 10,000장을 목표로
